### PR TITLE
Sorting Algorithms in Java

### PR DESCRIPTION
**Pull request by shrishail356**
Hi guys sorting is one of the main topics of data structures and algorithms , and in real world applications for sorting also , 
So here are some basic sorting algorithms written in JAVA , you can write it in any programming language you want by referring to the algorithm written here 
Hope this algo's help you guys, Thank you

### CODE REVIEW

**Comment by shrishail356** [comment]
Screenshot 2022-10-11 210510


Bro plz add the hacktoberfest-accepted lable while merging this pr , so as to not get excluded in hacktoberfest website 🙏

**Comment by kunalthedev** [comment]
Congrats ;)

**Comment by shrishail356** [comment]
bro can i get a t-shirt if my all4 pr get expected tommorow ?

**Comment by shrishail356** [comment]
excepted*

**Pull request merged**
